### ISSUE TITLE
石之家更新后无法使用扫码登录

### ISSUE THREAD

**Issue by bennyben123** [FF14CN/Sarean-arsenal#18]
### 问题描述

清除了原来config.ini里的rscookies和rs_cookies_expires后想重新登录石之家，发现qrcode.png一直无法正常重新生成

### 重现步骤

清除了config里的石之家的cookies数据后，重新运行一遍

### 截图

![error](https://github.com/FF14CN/Sarean-arsenal/assets/151617355/a1f9960d-66ce-4f89-bdb1-54acc4ecbc57)
![qrcode](https://github.com/FF14CN/Sarean-arsenal/assets/151617355/7c62b216-909a-4b2c-8c29-588022236139)

**Comment by Cettiidae** [comment]
Thank you for your feedback. We are currently investigating this issue! :)

**Comment by KuLiPoi** [comment]
已经确认问题，盛趣添加了Tencent Cloud EdgeOne (防火墙)，下次更新会彻底弃用扫码登录，以后只用叨鱼相关的参数就可以了，感谢反馈。

**Comment by KuLiPoi** [comment]
欢迎尝试一下新版，但是我们目前弃用了扫码登录的方式，如果在抓包上遇到了困难我们深感抱歉。你可以去diss一下沟槽的盛趣，如果后续还有问题欢迎欢迎继续追问。
