### ISSUE TITLE
尝试登录石之家，QRCode.py中出现报错

### ISSUE THREAD

**Issue by yulexun** [FF14CN/Sarean-arsenal#19]
### 问题描述

尝试进行石之家自动签到，推送显示cookie过期，终端中不显示登录二维码

### 重现步骤

1. 运行run.py，报错如下图显示
2. 将QRCode中打印二维码的代码单独复制出来，出现相同报错。

### 截图

![image](https://github.com/FF14CN/Sarean-arsenal/assets/74227776/0f62db07-ab69-4b32-9ee0-9c71506b90d9)
![屏幕截图 2024-06-28 162218](https://github.com/FF14CN/Sarean-arsenal/assets/74227776/c7f3f398-4e66-4ac1-b6fb-6d6ef09049d6)
![屏幕截图 2024-06-28 162312](https://github.com/FF14CN/Sarean-arsenal/assets/74227776/b8689f0f-d834-437a-97bd-abc2ef07b209)

### 运行环境

Windows Server 2022 21H2
python 3.12.2, 
软件版本2.0.3

**Comment by Cettiidae** [comment]
Thank you for your feedback. We are aware of the issue and confirm that it cannot be resolved, so we have decided to remove this login method in the next version. If you have better ideas, please feel free to communicate with us!  :）
same issue see #18 

————
感谢您的反馈，我们已知悉该问题，目前该问题无法解决。所以我们决定在下一个版本中移除该登录方式。如果您有更好的建议，欢迎与我们交流！ :）
相同的问题，请参见 #18

**Comment by KuLiPoi** [comment]
欢迎尝试一下新版，但是我们目前弃用了扫码登录的方式，如果在抓包上遇到了困难我们深感抱歉。~~你可以去diss一下沟槽的盛趣~~，如果后续还有问题欢迎欢迎继续追问。
