### ISSUE TITLE
新版签到青龙面板报错

### ISSUE THREAD

**Issue by bennyben123** [FF14CN/Sarean-arsenal#20]
### 问题描述

石之家和盛趣商城签到成功了，但青龙面板中日记返回信息石之家的信息会报错，使用server酱推送消息并不会显示石之家的签到结果

### 重现步骤

在青龙中运行qinglong.py

### 截图

![error](https://github.com/FF14CN/Sarean-arsenal/assets/151617355/2dc2104d-b096-4af8-82bc-885040da8810)

### 附加消息

在刚运行的时候，会显示命名错误，排查后发现是qinglong.py里，导入import依赖dailytask.py与项目文件内的名字大小写不一致，因改为from Utility.risingStones.dailyTask import daily_task as lets_go

**Comment by KuLiPoi** [comment]
我的，沉迷玩瓦，修复了应该，如果有问题欢迎继续跟进，感谢。

**Comment by bennyben123** [comment]
![error](https://github.com/FF14CN/Sarean-arsenal/assets/151617355/45e1e1bc-442c-4103-a030-87000d34187b)
试了试新版还有个报错，但这个账号2是用不上的，好像不影响

**Comment by KuLiPoi** [comment]
hi，我这边多个账户做了一下测试，没有复现这个问题，可以发一下你的logs文件吗，你可以把你自认为涉及隐私的部分用xxxxxxx代替一下，感谢。

**Comment by bennyben123** [comment]
[2024-07-04.0001.latest.log](https://github.com/user-attachments/files/16094980/2024-07-04.0001.latest.log)
辛苦了

**Comment by KuLiPoi** [comment]
hi 我这边看不出什么问题 请问你那个小号 如果在手机或者pc手动登录石之家有问题吗 游戏内有创建过角色吗

**Comment by bennyben123** [comment]
这个小号是没有创建过角色的小号，石之家没登录过，是叨鱼创建账号后自带的手机号账户

**Comment by KuLiPoi** [comment]
我又看了一下 是盛趣商城签到那边出了错，所以你这个也没登录过盛趣商城是吧..

**Comment by KuLiPoi** [comment]
如果不愿意重新下载 可以只替换 /utility/risingStones/下的 dailyTask.py和rs_login.py 感谢反馈
