### ISSUE TITLE
【推送】请问大佬可以多支持一个Qmsg推送服务吗

### ISSUE THREAD

**Issue by Clulu1499** [FF14CN/Sarean-arsenal#21]
### 在提问之前...

- [X] 我已确认当前请求的功能不在预订计划内，请查阅：https://github.com/orgs/FF14CN/projects/1

### 您的功能请求是否与当前存在问题有关？

由于我是安卓环境 现有的推送服务有些不会进行通知 所以想请大佬多添加一个推送服务

### 描述您想要的解决方案

https://qmsg.zendee.cn/docs/api/
这个是文档链接 如果可以的话 感激不尽——

**Comment by Cettiidae** [comment]
我们将为您添加此推送方式，请您关注稍后的更新 。

**Comment by Cettiidae** [comment]
🎉 已在v2.1.3的更新中添加改功能。配置方式与其他推送方式相同，增加两项qmsg专用配置：

```
;qmsg酱推送设置
;推送目标 normal=私聊  group=群聊
qmsg-target = normal
;推送目标QQ号/群号，留空默认全发
qmsg-target-number =
```
若使用过程中有任何问题和需求，请继续与我们沟通 🫡

**Comment by Clulu1499** [comment]
> 🎉 已在v2.1.3的更新中添加改功能。配置方式与其他推送方式相同，增加两项qmsg专用配置：
> 
> ```
> ;qmsg酱推送设置
> ;推送目标 normal=私聊  group=群聊
> qmsg-target = normal
> ;推送目标QQ号/群号，留空默认全发
> qmsg-target-number =
> ```
> 
> 若使用过程中有任何问题和需求，请继续与我们沟通 🫡

感谢大佬——
